xset -b
# Set Wallpaper 
xsetroot -solid "#777777"

# Activate .Xresources
xrdb -merge ~/.Xresources

# Set lower screen brightness
xrandr --output DVI-I-1 --brightness 0.7

# Execute WM
exec openbsd-cwm
